import { Mea_Culpa, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const meaCulpa = Mea_Culpa({
  style: ["normal"],
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mea-culpa",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${meaCulpa.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
